"""favorites table created

Revision ID: 019592e3328f
Revises: 42bfd2f11955
Create Date: 2023-05-05 16:05:38.493891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '019592e3328f'
down_revision = '42bfd2f11955'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('establishment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['establishment_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    # ### end Alembic commands ###
