"""test3

Revision ID: 180a564b90d6
Revises: 76e07f502963
Create Date: 2023-06-07 13:44:59.025691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '180a564b90d6'
down_revision = '76e07f502963'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_favorite_event',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('favorite_event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['favorite_event_id'], ['favorite_event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'favorite_event_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_favorite_event')
    # ### end Alembic commands ###
