"""test

Revision ID: 263f662c0aa0
Revises: 740dce55ea08
Create Date: 2023-06-07 13:09:17.620462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '263f662c0aa0'
down_revision = '740dce55ea08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorited_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['favorited_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_event', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('favorited_by')

    # ### end Alembic commands ###
