"""added zip_code to users

Revision ID: 42bfd2f11955
Revises: 2c2c2bfe778e
Create Date: 2023-05-05 12:35:45.652872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42bfd2f11955'
down_revision = '2c2c2bfe778e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zip_code', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('zip_code')

    # ### end Alembic commands ###
