"""added a junction table

Revision ID: 43d410c79e77
Revises: d497f4269fca
Create Date: 2023-04-28 12:43:17.882441

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '43d410c79e77'
down_revision = 'd497f4269fca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('establishment_teams',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_ibfk_1', type_='foreignkey')
        batch_op.drop_column('team_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('user_ibfk_1', 'team', ['team_id'], ['id'])

    op.drop_table('establishment_teams')
    # ### end Alembic commands ###
