"""removed last name field to accomodate establishment names instead of just first/last name

Revision ID: 4adce881866c
Revises: ef72aa3b4cea
Create Date: 2023-04-27 10:02:34.583004

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4adce881866c'
down_revision = 'ef72aa3b4cea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', mysql.VARCHAR(length=255), nullable=False))

    # ### end Alembic commands ###
