"""updated review to create reviewee vs reviewer

Revision ID: 6e5a8eec8a3b
Revises: 4544b1b721c7
Create Date: 2023-05-31 13:48:30.988688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e5a8eec8a3b'
down_revision = '4544b1b721c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewee_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['reviewee_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('reviewee_id')

    # ### end Alembic commands ###
