"""add date to reviews

Revision ID: 740dce55ea08
Revises: 6e5a8eec8a3b
Create Date: 2023-06-02 12:29:52.769811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '740dce55ea08'
down_revision = '6e5a8eec8a3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
