"""test2

Revision ID: 76e07f502963
Revises: 263f662c0aa0
Create Date: 2023-06-07 13:15:39.619823

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '76e07f502963'
down_revision = '263f662c0aa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorited_by_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('favorite_event_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['favorited_by_id'], ['id'])
        batch_op.drop_column('favorited_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorited_by', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorite_event_ibfk_2', 'user', ['favorited_by'], ['id'])
        batch_op.drop_column('favorited_by_id')

    # ### end Alembic commands ###
