"""Establishment name missing

Revision ID: 782306fd91f4
Revises: 40eb1437ef25
Create Date: 2023-04-28 14:21:04.240272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '782306fd91f4'
down_revision = '40eb1437ef25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('establishment_name', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['establishment_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('establishment_name')

    # ### end Alembic commands ###
