"""made events its own table

Revision ID: dde617b0cade
Revises: 82dda3c96da0
Create Date: 2023-04-27 13:35:48.320693

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dde617b0cade'
down_revision = '82dda3c96da0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('event', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('event_image', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('event')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('event')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event', mysql.VARCHAR(length=255), nullable=True))

    op.drop_table('event')
    # ### end Alembic commands ###
