"""Init 2

Revision ID: ef72aa3b4cea
Revises: c4d7f9729c0f
Create Date: 2023-04-27 09:23:50.397117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef72aa3b4cea'
down_revision = 'c4d7f9729c0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('league', sa.String(length=100), nullable=False),
    sa.Column('division', sa.String(length=100), nullable=True),
    sa.Column('conference', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fan',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=225), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_establishment', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('opening_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('closing_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('menu_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('specials', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('event', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('social_media', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('entertainment', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('team_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_foreign_key(None, 'team', ['team_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('team_id')
        batch_op.drop_column('entertainment')
        batch_op.drop_column('social_media')
        batch_op.drop_column('event')
        batch_op.drop_column('specials')
        batch_op.drop_column('menu_url')
        batch_op.drop_column('closing_time')
        batch_op.drop_column('opening_time')
        batch_op.drop_column('is_establishment')

    op.drop_table('fan')
    op.drop_table('team')
    op.drop_table('review')
    # ### end Alembic commands ###
